### Numpy
NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

In [1]:
import numpy as np

In [2]:
##Creating arrays using numpy (1-D)
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [3]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape((1,5)) #converting to a 2-d array (1 row and 5 coloumns)

array([[1, 2, 3, 4, 5]])

In [4]:
#Creating a 2-D array
arr2=np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [6]:
##2-D Array
arr2=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr2)
print(arr2.dtype)
print(arr2.shape)

[[1 2 3 4 5]
 [1 2 3 4 5]]
int64
(2, 5)
