In [3]:
import numpy as np

In [4]:
#Creating array with the inbuilt function
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [5]:
##Creates an 2-D array of 3 rows and 4 coloums with 1 as the element 
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
##creaating an identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
#Attributes of numpy array
arr = np.array([[1,2,3,],[4,5,6]])

print("Array: \n",arr)
print("Shape: ",arr.shape)
print("Number of dimensions: ",arr.ndim)
print("Size (number of elements): ",arr.size)
print("Data type: ",arr.dtype)
print("Item size (in bytes): ",arr.itemsize)

Array: 
 [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
Number of dimensions:  2
Size (number of elements):  6
Data type:  int64
Item size (in bytes):  8


In [8]:
##Numpy vectorized operations
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

##Element wise adding 
print("Addition: ",arr1+arr2)

##Element wise substraction
print("Substraction: ",arr1-arr2)

# Element wise multiplication
print("Multiplication: ",arr1 * arr2)

# Element wise division
print("Division: ",arr1 / arr2)

Addition:  [11 22 33 44 55]
Substraction:  [ -9 -18 -27 -36 -45]
Multiplication:  [ 10  40  90 160 250]
Division:  [0.1 0.1 0.1 0.1 0.1]


In [9]:
##Universal function
arr=np.array([2,3,4,5,6])

##Square root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## Sine
print(np.sin(arr))

## natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]
