In [1]:
import numpy as np

In [2]:
##Array slicing and indexing 
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array: \n",arr)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [3]:
print(arr[0][0])
print(arr[0:2,2:])

1
[[3 4]
 [7 8]]


In [4]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [5]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [6]:
##Modify array elements
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [7]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]
